### ISSUE TITLE
Build error with default settings

### ISSUE THREAD

**Issue by lassoan** [mstaring/elastix#11]
I'm working on developing an extension 3D Slicer to make Elastix registration available directly using Slicer's GUI.

Unfortunately, first build attempt of Elastix always fails with this error:

> c:\d\elx-win64rel\elastix\src\common\knn\itkBinaryANNTreeBase.h(22): fatal error C1083: Cannot open include file: 'ANN/ANN.h': No such file or directory [C:\D\Elx-win64rel\elastix-build\Components\Metrics\KNNGraphAlphaMutualInformation\KNNGraphAlphaMutualInformationMetric.vcxproj] [C:\D\Elx-win64rel\elastix.vcxproj]

This was reported by others, too, for example here:
http://lists.bigr.nl/pipermail/elastix/2016-July/002328.html

Second (and subsequent) build attempts are successful.

The problem is that at configuration time, USE_KNNGraphAlphaMutualInformationMetric is OFF, therefore elastix\src\Common\KNN directory is not processed, therefore ANN.h is not generated. However, later, ADD_ELXCOMPONENT( KNNGraphAlphaMutualInformationMetric ...) needs ANN.h file. 

The solution may be to skip ADD_ELXCOMPONENT( KNNGraphAlphaMutualInformationMetric if USE_KNNGraphAlphaMutualInformationMetric is OFF; or make sure that if KNNGraphAlphaMutualInformationMetric component is enabled then it turns on USE_KNNGraphAlphaMutualInformationMetric _before_ elastix\src\Common is configured.

**Comment by kaspermarstal** [comment]
Hi @lassoan! Thank you for your input! This will be fixed in the next release.

**Comment by mstaring** [comment]
This was fixed in commit f20867ffdfd38d439b12eb351b39b2ca8b36705d

**Comment by lassoan** [comment]
thank you!
