### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by mys007** [mstaring/elastix#3]
The current state doesn't compile (as a shared library on Ubuntu 14.04). Necessary changes:
- add `#include "itkOpenCLUtil.h"` to `itkGPUUnaryFunctorImageFilter.hxx`
- add `void AddParameterFile( const ParameterFileNameType parameterFileName );` to `elxParameterObject.h`
- add `-fPIC` to `CMAKE_CXX_FLAGS`

**Comment by mstaring** [comment]
Thank you for reporting this. please check if the latest trunk works for you
