### ISSUE TITLE
elastix doesn't build with the upcoming g++6.0 

### ISSUE THREAD

**Issue by gerddie** [mstaring/elastix#5]
In short, you are using the *itkTypeMacro*, that defines the method *GetNameOfClass()* that uses the method specifier [override](http://en.cppreference.com/w/cpp/language/override) that is enabled in ITK when compiled with the c++11 or a newer C++ dialect, and g++6.0  defaults to c++14. 
Since none of the parent classes defines this method *GetNameOfClass()* this *override* is not a real override, hence the error.

There are three option to get this to compile with c++11 enabled: 

* don't use *itkTypeMacro*
* declare the *GetNameOfClass()* as a virtual method in the respective base classe
* derive the base class from *itkLightObject*

To test your changes it should be possible to just set the *-std=c++11* compiler flag and see whether it compiles. 

For the Debian package I will go the easy way and enforce *-std=c++03* to avoid that *override* is used at all, but at some moment ITK may require c++11 ... 

For more details please see the debian bug [#822713](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822713). 

best regards, 
Gert

**Comment by mstaring** [comment]
This seems more like an ITK issue, would you agree?
Perhaps they should change the definition of the TypeMacro?

**Comment by gerddie** [comment]
One could ask ITK upstream that they drop the *override* specifier for *GetNameOfClass()* in their *itkTypeMacro*, but somehow this is going backwards (i.e. this is a new c++11 feature they just added there),. 

I didn't ask ITK upstream about this, because  I figured that their answer would be that someone using the *itkTypeMacro* in their code will have to make sure that it fulfils certain requirements, in this case that the base class declares a virtual method *GetNameOfClass()*. Obviously within ITK this is the case since they seem to have build their class hierarchy with *itkLightObject* as root. 

For that reason I think the easiest way out is the second option I gave above, declaring an abstract method *GetNameOfClass()* with the according signature in the base class you use in the *itkTypeMacro*.

Best, 
Gert

**Comment by mstaring** [comment]
ok, can you check if commit
https://github.com/mstaring/elastix/commit/d289960c99bbee861449c6cffc710b6065fb78a5
fixes the issue for you?

I used itkTypeMacroNoParent to define a GetNameOfClass function higher up.

**Comment by gerddie** [comment]
Okay, I'll get back to you.

**Comment by gerddie** [comment]
Issue fixed.
