### ISSUE TITLE
Installation instructions for macOS

### ISSUE THREAD

**Issue by thomasaarholt** [mstaring/elastix#7]
If you would like to add installation instructions for Mac, they are the same as for linux, but the PATH variables are:

```bash
export PATH=path/to/bin:$PATH
export DYLD_LIBRARY_PATH=path/to/lib:$PATH
```

**Comment by mstaring** [comment]
Hi Thomas, it seems this is already in the manual:
https://github.com/mstaring/elastix/blob/master/dox/manual/manual.tex#L1178
Can you confirm if this is what you mean?

**Comment by thomasaarholt** [comment]
Aha. Well, that is not the same version as the manual in pdf form online (which I see now is from 2015):
http://elastix.isi.uu.nl/download/elastix_manual_v4.8.pdf
It is linked to in the [FAQ](http://elastix.isi.uu.nl/FAQ.php) and the [main page](http://elastix.isi.uu.nl/index.php).

**Comment by mstaring** [comment]
yes indeed, we should make a new release

**Comment by thomasaarholt** [comment]
We use https://readthedocs.org/ for our documentation, and it will let a user build the latest version automatically. Can recommend.

**Comment by mstaring** [comment]
We have started with it as well, see http://superelastix.readthedocs.io
